### ISSUE TITLE
variable ner undefined when compiling

### ISSUE THREAD

**Issue by spatzle** [dat/stanford-ner#1]
rm -fR tmp
mkdir tmp
mkdir -p tmp/META-INF tmp/WEB-INF
mkdir -p tmp/WEB-INF/classes tmp/WEB-INF/lib tmp/WEB-INF/resources
mkdir -p tmp/WEB-INF/resources/classifiers
cp classifiers/_.ser.gz tmp/WEB-INF/resources/classifiers
cp extra/index.html tmp
cp extra/LICENSE.txt tmp/META-INF
cp extra/web.xml tmp/WEB-INF
javac -O -d tmp/WEB-INF/classes \
                -classpath /opt/search/lucidworks/jetty/lib/servlet-api-2.5-6.1.3.jar \
                src/edu/stanford/nlp/_/_.java src/edu/stanford/nlp/_/_/_.java \
                src/com/ntrepid/tartan/_.java
src/com/ntrepid/tartan/NERServlet.java:109: cannot find symbol
symbol  : variable ner
location: class com.ntrepid.tartan.NERServlet
        AbstractSequenceClassifier tagger = ner.get(classifier);
                                            ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
make: *_\* [war] Error 1

**Comment by dat** [comment]
Simple variable spelling mistake. Code fixed. Please check the latest update. Thanks.
