### ISSUE TITLE
make fails with "..unclosed character literal"

### ISSUE THREAD

**Issue by cybertoast** [dat/stanford-ner#3]
On OSX 10.8.x, when running `make` the following error is returned:

```
src/edu/stanford/nlp/process/WordShapeClassifier.java:492: unclosed character literal
```

The solution is to add the following to the JAVAFLAGS option in the Makefile:

```
JAVAFLAGS = -O -encoding UTF8
```

**Comment by cybertoast** [comment]
The above comment is purely informational, and should probably be added to the README, so closing this ticket as a reference for others who have this issue.

**Comment by seanlavelle** [comment]
Shouldn't that encoding flag be there all the time? why not make this a pull request
